<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../WatchCollection.Infrastructure/WatchCollection.Infrastructure.csproj" />
      <ProjectReference Include="../WatchCollection.Shared/WatchCollection.Shared.csproj" />
      <ProjectReference Include="../WatchCollection.Storage.Entities/WatchCollection.Storage.Entities.csproj" />
    </ItemGroup>

</Project>
