<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
        <PackageReference Include="Azure.Identity" Version="1.17.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../WatchCollection.Api.Contracts/WatchCollection.Api.Contracts.csproj" />
      <ProjectReference Include="../WatchCollection.Domain.Services/WatchCollection.Domain.Services.csproj" />
      <ProjectReference Include="../WatchCollection.Storage.Entities/WatchCollection.Storage.Entities.csproj" />
      <ProjectReference Include="../WatchCollection/WatchCollection.Infrastructure/WatchCollection.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Middleware/" />
    </ItemGroup>

</Project>
