<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../WatchValuation.Api.Contracts/WatchValuation.Api.Contracts.csproj" />
      <ProjectReference Include="../WatchValuation.Domain.Services/WatchValuation.Domain.Services.csproj" />
    </ItemGroup>

</Project>
